### ISSUE TITLE
`npm start` crashing on me...

### ISSUE THREAD

**Issue by cymen** [coodoo/react-redux-isomorphic-example#15]
I got everything installed but when I try to do `npm start`:

``` sh
$ npm start

> react-redux-isomprphic-example@1.0.0 start /Users/cymen/dev/react-redux-isomorphic-example
> npm run build& nodemon server

[nodemon] 1.8.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node --stage 0 server dev.js`

> react-redux-isomprphic-example@1.0.0 build /Users/cymen/dev/react-redux-isomorphic-example
> webpack -d --progress --watch

 30% 1/3 build modulesmodule.js:338
    throw err;
          ^
Error: Cannot find module '/Users/cymen/dev/react-redux-isomorphic-example/0'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at /usr/local/lib/node_modules/babel-cli/lib/_babel-node.js:161:27
    at Object.<anonymous> (/usr/local/lib/node_modules/babel-cli/lib/_babel-node.js:162:7)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
[nodemon] app crashed - waiting for file changes before starting...
Hash: d445f68a82f051ff82bb
Version: webpack 1.12.4
Time: 4031ms
        Asset     Size  Chunks             Chunk Names
    bundle.js  1.49 MB       0  [emitted]  main
bundle.js.map  1.62 MB       0  [emitted]  main
   [0] multi main 40 bytes {0} [built]
    + 458 hidden modules
[nodemon] restarting due to changes...
[nodemon] starting `babel-node --stage 0 server dev.js`
module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/cymen/dev/react-redux-isomorphic-example/0'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at /usr/local/lib/node_modules/babel-cli/lib/_babel-node.js:161:27
    at Object.<anonymous> (/usr/local/lib/node_modules/babel-cli/lib/_babel-node.js:162:7)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
[nodemon] app crashed - waiting for file changes before starting...
```

Do I need to use a newer version of node? I'm on v0.12.7.

**Comment by cymen** [comment]
I tried node v5.0.0 and same problem so far.

**Comment by coodoo** [comment]
I just did a clean install and everything ran fine, one thing to note though you might need to lock the version  of globally installed `babel-cli` to `5.8.23`, for that the latest v6 has some issues which I prefer not to use at this moment.

You can check your installed version by `babel-node --version`.

**Comment by johannes-photobox** [comment]
I have same error on `node 4.2.2` and `babel-cli 6.1.2`.

I can imagine a lot of people are running into the same problem. I don't think to use babel 5.x is a viable solution (correct me if I misunderstood this). I would consider a reopen...

**Comment by davidroman0O** [comment]
The problem is still here. 
You should try to execute the server on an new environment to check this kind of errors.

**Comment by coodoo** [comment]
I just updated the project, removed dependency on globally installed `babel`, and did a clean install which went pretty well, could any one who's still suffering from the issue try again and let me how it goes? Thanks.
